// Generated by jextract

package org.rknn;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _rknn_init_extend {
 *     rknn_context ctx;
 *     int32_t real_model_offset;
 *     uint32_t real_model_size;
 *     uint8_t reserved[120];
 * }
 * }
 */
public class _rknn_init_extend {

    _rknn_init_extend() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        rknn_matmul_api_h.C_LONG.withName("ctx"),
        rknn_matmul_api_h.C_INT.withName("real_model_offset"),
        rknn_matmul_api_h.C_INT.withName("real_model_size"),
        MemoryLayout.sequenceLayout(120, rknn_matmul_api_h.C_CHAR).withName("reserved")
    ).withName("_rknn_init_extend");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong ctx$LAYOUT = (OfLong)$LAYOUT.select(groupElement("ctx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * rknn_context ctx
     * }
     */
    public static final OfLong ctx$layout() {
        return ctx$LAYOUT;
    }

    private static final long ctx$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * rknn_context ctx
     * }
     */
    public static final long ctx$offset() {
        return ctx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * rknn_context ctx
     * }
     */
    public static long ctx(MemorySegment struct) {
        return struct.get(ctx$LAYOUT, ctx$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * rknn_context ctx
     * }
     */
    public static void ctx(MemorySegment struct, long fieldValue) {
        struct.set(ctx$LAYOUT, ctx$OFFSET, fieldValue);
    }

    private static final OfInt real_model_offset$LAYOUT = (OfInt)$LAYOUT.select(groupElement("real_model_offset"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int32_t real_model_offset
     * }
     */
    public static final OfInt real_model_offset$layout() {
        return real_model_offset$LAYOUT;
    }

    private static final long real_model_offset$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int32_t real_model_offset
     * }
     */
    public static final long real_model_offset$offset() {
        return real_model_offset$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int32_t real_model_offset
     * }
     */
    public static int real_model_offset(MemorySegment struct) {
        return struct.get(real_model_offset$LAYOUT, real_model_offset$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int32_t real_model_offset
     * }
     */
    public static void real_model_offset(MemorySegment struct, int fieldValue) {
        struct.set(real_model_offset$LAYOUT, real_model_offset$OFFSET, fieldValue);
    }

    private static final OfInt real_model_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("real_model_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t real_model_size
     * }
     */
    public static final OfInt real_model_size$layout() {
        return real_model_size$LAYOUT;
    }

    private static final long real_model_size$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t real_model_size
     * }
     */
    public static final long real_model_size$offset() {
        return real_model_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t real_model_size
     * }
     */
    public static int real_model_size(MemorySegment struct) {
        return struct.get(real_model_size$LAYOUT, real_model_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t real_model_size
     * }
     */
    public static void real_model_size(MemorySegment struct, int fieldValue) {
        struct.set(real_model_size$LAYOUT, real_model_size$OFFSET, fieldValue);
    }

    private static final SequenceLayout reserved$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("reserved"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t reserved[120]
     * }
     */
    public static final SequenceLayout reserved$layout() {
        return reserved$LAYOUT;
    }

    private static final long reserved$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t reserved[120]
     * }
     */
    public static final long reserved$offset() {
        return reserved$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t reserved[120]
     * }
     */
    public static MemorySegment reserved(MemorySegment struct) {
        return struct.asSlice(reserved$OFFSET, reserved$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t reserved[120]
     * }
     */
    public static void reserved(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, reserved$OFFSET, reserved$LAYOUT.byteSize());
    }

    private static long[] reserved$DIMS = { 120 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * uint8_t reserved[120]
     * }
     */
    public static long[] reserved$dimensions() {
        return reserved$DIMS;
    }
    private static final VarHandle reserved$ELEM_HANDLE = reserved$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * uint8_t reserved[120]
     * }
     */
    public static byte reserved(MemorySegment struct, long index0) {
        return (byte)reserved$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * uint8_t reserved[120]
     * }
     */
    public static void reserved(MemorySegment struct, long index0, byte fieldValue) {
        reserved$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

