// Generated by jextract

package org.rknn;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _rknn_run_extend {
 *     uint64_t frame_id;
 *     int32_t non_block;
 *     int32_t timeout_ms;
 *     int32_t fence_fd;
 * } rknn_run_extend
 * }
 */
public class rknn_run_extend extends _rknn_run_extend {

    rknn_run_extend() {
        // Should not be called directly
    }
}

