// Generated by jextract

package org.rknn;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _rknn_input_range {
 *     uint32_t index;
 *     uint32_t shape_number;
 *     rknn_tensor_format fmt;
 *     char name[256];
 *     uint32_t dyn_range[512][16];
 *     uint32_t n_dims;
 * } rknn_input_range
 * }
 */
public class rknn_input_range extends _rknn_input_range {

    rknn_input_range() {
        // Should not be called directly
    }
}

