// Generated by jextract

package org.rknn;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _rknn_matmul_shape {
 *     int32_t M;
 *     int32_t K;
 *     int32_t N;
 * } rknn_matmul_shape
 * }
 */
public class rknn_matmul_shape extends _rknn_matmul_shape {

    rknn_matmul_shape() {
        // Should not be called directly
    }
}

