// Generated by jextract

package org.rknn;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _rknn_custom_string {
 *     char string[1024];
 * } rknn_custom_string
 * }
 */
public class rknn_custom_string extends _rknn_custom_string {

    rknn_custom_string() {
        // Should not be called directly
    }
}

