// Generated by jextract

package org.rknn;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _rknn_matmul_io_attr {
 *     rknn_matmul_tensor_attr A;
 *     rknn_matmul_tensor_attr B;
 *     rknn_matmul_tensor_attr C;
 * } rknn_matmul_io_attr
 * }
 */
public class rknn_matmul_io_attr extends _rknn_matmul_io_attr {

    rknn_matmul_io_attr() {
        // Should not be called directly
    }
}

