// Generated by jextract

package org.rknn;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _rknn_mem_size {
 *     uint32_t total_weight_size;
 *     uint32_t total_internal_size;
 *     uint64_t total_dma_allocated_size;
 *     uint32_t total_sram_size;
 *     uint32_t free_sram_size;
 *     uint32_t reserved[10];
 * } rknn_mem_size
 * }
 */
public class rknn_mem_size extends _rknn_mem_size {

    rknn_mem_size() {
        // Should not be called directly
    }
}

