// Generated by jextract

package org.rknn;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _rknn_perf_run {
 *     int64_t run_duration;
 * } rknn_perf_run
 * }
 */
public class rknn_perf_run extends _rknn_perf_run {

    rknn_perf_run() {
        // Should not be called directly
    }
}

