// Generated by jextract

package org.rknn;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _rknn_tensor_attr {
 *     uint32_t index;
 *     uint32_t n_dims;
 *     uint32_t dims[16];
 *     char name[256];
 *     uint32_t n_elems;
 *     uint32_t size;
 *     rknn_tensor_format fmt;
 *     rknn_tensor_type type;
 *     rknn_tensor_qnt_type qnt_type;
 *     int8_t fl;
 *     int32_t zp;
 *     float scale;
 *     uint32_t w_stride;
 *     uint32_t size_with_stride;
 *     uint8_t pass_through;
 *     uint32_t h_stride;
 * } rknn_tensor_attr
 * }
 */
public class rknn_tensor_attr extends _rknn_tensor_attr {

    rknn_tensor_attr() {
        // Should not be called directly
    }
}

