// Generated by jextract

package org.rknn;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _rknn_perf_detail {
 *     char *perf_data;
 *     uint64_t data_len;
 * }
 * }
 */
public class _rknn_perf_detail {

    _rknn_perf_detail() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        rknn_matmul_api_h.C_POINTER.withName("perf_data"),
        rknn_matmul_api_h.C_LONG.withName("data_len")
    ).withName("_rknn_perf_detail");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout perf_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("perf_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *perf_data
     * }
     */
    public static final AddressLayout perf_data$layout() {
        return perf_data$LAYOUT;
    }

    private static final long perf_data$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *perf_data
     * }
     */
    public static final long perf_data$offset() {
        return perf_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *perf_data
     * }
     */
    public static MemorySegment perf_data(MemorySegment struct) {
        return struct.get(perf_data$LAYOUT, perf_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *perf_data
     * }
     */
    public static void perf_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(perf_data$LAYOUT, perf_data$OFFSET, fieldValue);
    }

    private static final OfLong data_len$LAYOUT = (OfLong)$LAYOUT.select(groupElement("data_len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t data_len
     * }
     */
    public static final OfLong data_len$layout() {
        return data_len$LAYOUT;
    }

    private static final long data_len$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t data_len
     * }
     */
    public static final long data_len$offset() {
        return data_len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t data_len
     * }
     */
    public static long data_len(MemorySegment struct) {
        return struct.get(data_len$LAYOUT, data_len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t data_len
     * }
     */
    public static void data_len(MemorySegment struct, long fieldValue) {
        struct.set(data_len$LAYOUT, data_len$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

