// Generated by jextract

package org.rknn;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _rknn_input_output_num {
 *     uint32_t n_input;
 *     uint32_t n_output;
 * }
 * }
 */
public class _rknn_input_output_num {

    _rknn_input_output_num() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        rknn_matmul_api_h.C_INT.withName("n_input"),
        rknn_matmul_api_h.C_INT.withName("n_output")
    ).withName("_rknn_input_output_num");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt n_input$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_input"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_input
     * }
     */
    public static final OfInt n_input$layout() {
        return n_input$LAYOUT;
    }

    private static final long n_input$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_input
     * }
     */
    public static final long n_input$offset() {
        return n_input$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_input
     * }
     */
    public static int n_input(MemorySegment struct) {
        return struct.get(n_input$LAYOUT, n_input$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_input
     * }
     */
    public static void n_input(MemorySegment struct, int fieldValue) {
        struct.set(n_input$LAYOUT, n_input$OFFSET, fieldValue);
    }

    private static final OfInt n_output$LAYOUT = (OfInt)$LAYOUT.select(groupElement("n_output"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t n_output
     * }
     */
    public static final OfInt n_output$layout() {
        return n_output$LAYOUT;
    }

    private static final long n_output$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t n_output
     * }
     */
    public static final long n_output$offset() {
        return n_output$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t n_output
     * }
     */
    public static int n_output(MemorySegment struct) {
        return struct.get(n_output$LAYOUT, n_output$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t n_output
     * }
     */
    public static void n_output(MemorySegment struct, int fieldValue) {
        struct.set(n_output$LAYOUT, n_output$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction) (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

