// Generated by jextract

package org.rknn;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _rknn_input {
 *     uint32_t index;
 *     void *buf;
 *     uint32_t size;
 *     uint8_t pass_through;
 *     rknn_tensor_type type;
 *     rknn_tensor_format fmt;
 * } rknn_input
 * }
 */
public class rknn_input extends _rknn_input {

    rknn_input() {
        // Should not be called directly
    }
}

