// Generated by jextract

package org.rknn;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _rknn_perf_detail {
 *     char *perf_data;
 *     uint64_t data_len;
 * } rknn_perf_detail
 * }
 */
public class rknn_perf_detail extends _rknn_perf_detail {

    rknn_perf_detail() {
        // Should not be called directly
    }
}

