// Generated by jextract

package org.rknn;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _rknn_input_output_num {
 *     uint32_t n_input;
 *     uint32_t n_output;
 * } rknn_input_output_num
 * }
 */
public class rknn_input_output_num extends _rknn_input_output_num {

    rknn_input_output_num() {
        // Should not be called directly
    }
}

