// Generated by jextract

package org.rknn;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _rknn_init_extend {
 *     rknn_context ctx;
 *     int32_t real_model_offset;
 *     uint32_t real_model_size;
 *     uint8_t reserved[120];
 * } rknn_init_extend
 * }
 */
public class rknn_init_extend extends _rknn_init_extend {

    rknn_init_extend() {
        // Should not be called directly
    }
}

