// Generated by jextract

package org.rknn;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _rknn_output_extend {
 *     uint64_t frame_id;
 * } rknn_output_extend
 * }
 */
public class rknn_output_extend extends _rknn_output_extend {

    rknn_output_extend() {
        // Should not be called directly
    }
}

