// Generated by jextract

package org.rknn;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _rknn_matmul_tensor_attr {
 *     char name[256];
 *     uint32_t n_dims;
 *     uint32_t dims[16];
 *     uint32_t size;
 *     rknn_tensor_type type;
 * } rknn_matmul_tensor_attr
 * }
 */
public class rknn_matmul_tensor_attr extends _rknn_matmul_tensor_attr {

    rknn_matmul_tensor_attr() {
        // Should not be called directly
    }
}

