// Generated by jextract

package org.rknn;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _rknn_quant_params {
 *     char name[256];
 *     float *scale;
 *     int32_t scale_len;
 *     int32_t *zp;
 *     int32_t zp_len;
 * } rknn_quant_params
 * }
 */
public class rknn_quant_params extends _rknn_quant_params {

    rknn_quant_params() {
        // Should not be called directly
    }
}

